"""initial

Revision ID: 5ae768c805c6
Revises: 
Create Date: 2023-09-16 17:04:59.723534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae768c805c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('middlename', sa.String(), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', name='sex'), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('encoding', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_data',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('video_filename', sa.String(), nullable=False),
    sa.Column('crop_filename', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'video_filename')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_data')
    op.drop_table('user_profile')
    # ### end Alembic commands ###
